language: csharp

os:
  - linux

branches:
  only:
    - master

dist: trusty
mono: none
dotnet: 2.1.500

solution: Machine.Specifications.sln

script:
  - dotnet test Source/Machine.Specifications.Specs --framework netcoreapp2.1
  - dotnet test Source/Machine.Specifications.Tests --framework netcoreapp2.1
