language: csharp

os:
  - linux

branches:
  only:
    - master

dist: trusty
mono: latest

solution: Machine.Specifications.sln

script:
  - dotnet test Source\Machine.Specifications.Specs --framework netcoreapp2.1
  - dotnet test Source\Machine.Specifications.Tests --framework netcoreapp2.1
