<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableMSpecSourceGeneration>false</EnableMSpecSourceGeneration>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Machine.Specifications.Core\Machine.Specifications.Core.csproj" />
    <ProjectReference Include="..\..\src\Machine.Specifications.Should\Machine.Specifications.Should.csproj" />
  </ItemGroup>

</Project>
