using System.Text;
using Microsoft.CodeAnalysis;

namespace Machine.Specifications.Core.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public class InfrastructureGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enabled = context.AnalyzerConfigOptionsProvider
            .Select((options, _) =>
            {
                options.GlobalOptions.TryGetValue("build_property.EnableMSpecSourceGeneration", out var value);

                return !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);
            });

        var provider = context.CompilationProvider
            .Select((compilation, _) => new AssemblyInfo
            {
                AssemblyName = compilation.Assembly.Name
            })
            .Combine(enabled);

        context.RegisterSourceOutput(provider, (sourceContext, info) =>
        {
            var writer = new StringBuilder();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#pragma warning disable");

            sourceContext.AddSource("MSpecInfrastructure.g.cs", writer.ToString());
        });
    }

    private class AssemblyInfo
    {
        public string AssemblyName { get; set; } = string.Empty;
    }
}
