<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Machine.Specifications</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Machine.Specifications is a Context/Specification framework geared towards removing language noise and simplifying tests</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
  </ItemGroup>

</Project>
