<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Machine.Specifications</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Machine.Specifications is a Context/Specification framework geared towards removing language noise and simplifying tests</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport.Abstractions" Version="2.4.1" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="2.4.1" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Machine.Specifications.Core.SourceGenerator\Machine.Specifications.Core.SourceGenerator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <TfmSpecificPackageFile Include="$(TargetDir)$(AssemblyName).SourceGenerator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
  </ItemGroup>

</Project>
