<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <RootNamespace>Machine.Specifications</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Machine.Specifications is a Context/Specification framework geared towards removing language noise and simplifying tests</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport.Abstractions" Version="1.6.2" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="1.6.2" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Machine.Specifications.Core.props" PackagePath="build/$(TargetFramework)" Pack="true" />
    <None Include="Machine.Specifications.Core.targets" PackagePath="buildTransitive/$(TargetFramework)" Pack="true" />
  </ItemGroup>

</Project>
