name: build

on:
  push:
    branches:
      - master
  pull_request:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]

    name: Build ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Build ps1
        if: contains(matrix.runs-on, 'windows')
        run: ./build.cmd
      - name: Build bash
        if: contains(matrix.runs-on, 'macos') || contains(matrix.runs-on, 'ubuntu')
        run: ./build.sh
      - name: Upload artifacts
        if: contains(matrix.runs-on, 'ubuntu')
        uses: actions/upload-artifact@v2
        with:
          path: artifacts/*.nupkg
